#! /bin/sh

# killall
killall -q sxhkd
killall -q polybar

# start monitors
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --output eDP-1-1 --auto --gamma 0.8:0.8:0.8 --brightness 0.8 --output HDMI-0 --primary --auto --left-of eDP-1-1

bspc monitor eDP-1-1 -d cmd www im dev media vbox doc
bspc monitor HDMI-0 -d cmd www im dev media vbox doc

# Colors
AZURE="#80d9d8"
NORMAL_BORDER_COLOR="#5b5558"
ACTIVE_BORDER_COLOR="#262734"
PRESEL_FEEDBACK_COLOR="#D6A36A"

bspc config border_width          1
bspc config window_gap            18
Bspc config normal_border_color   "$NORMAL_BORDER_COLOR"
bspc config active_border_color   "$ACTIVE_BORDER_COLOR"
bspc config focused_border_color  "$AZURE"
bspc config presel_feedback_color "$PRESEL_FEEDBACK_COLOR"
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config single_monocle true
bspc config ignore_ewmh_focus true

bspc config removal_adjustment true
bspc config initial_polarity first_child
bspc config automatic_scheme spiral

bspc config split_ratio           0.6
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

# Application Rules
bspc rule -a Google-chrome          desktop='^2' follow=off
bspc rule -a Pcmanfm                desktop='^5' follow=off
bspc rule -a Evince                 desktop='^6' follow=off
bspc rule -a "VirtualBox Manager"   desktop='^6' follow=off

# Autostart Apps
nvidia-settings --assign CurrentMetaMode="nvidia-auto-select +0+0 { ForceFullCompositionPipeline = On }" &
sxhkd &
setxkbmap -layout pt &
xsetroot -cursor_name left_ptr &
ssh-agent &
ssh-add ~/.ssh/id_rsa &
light -S 60 &
setxkbmap -layout pt &
lxqt-policykit-agent &
feh --bg-scale /mnt/Data/Wallpapers/moon.jpg &
$HOME/.config/polybar/launch.sh