#! /bin/bash

C() { bspc config "$@";  }
R() { bspc rule -a "$@"; }
S() { pkill -x "$1"; { sleep 0.1; "$@" & }; }

# start monitors
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --output eDP-1-1 --auto --gamma 0.8:0.8:0.8 --brightness 0.8 --output HDMI-0 --primary --auto --left-of eDP-1-1

bspc monitor eDP-1-1 -d cmd www im dev media vbox doc
bspc monitor HDMI-0 -d cmd www im dev media vbox doc

# Colors
AZURE="#80d9d8"
NORMAL_BORDER_COLOR="#5b5558"
ACTIVE_BORDER_COLOR="#262734"
PRESEL_FEEDBACK_COLOR="#D6A36A"

C border_width          1
C window_gap            12
C normal_border_color   "$NORMAL_BORDER_COLOR"
C active_border_color   "$ACTIVE_BORDER_COLOR"
C focused_border_color  "$AZURE"
C presel_feedback_color "$PRESEL_FEEDBACK_COLOR"
C focus_by_distance             true
C focus_follows_pointer         true
C single_monocle true
C ignore_ewmh_focus true
C pointer_follows_monitor true

C removal_adjustment true
C initial_polarity first_child
C automatic_scheme spiral

C split_ratio           0.55
C borderless_monocle    true
C gapless_monocle       true
C focus_follows_pointer true

bspc rule -r "*"
# Application Rules
R Chromium               desktop='^2' follow=off
R Evince                 desktop='^7' follow=off
R "VirtualBox Manager"   desktop='^6' follow=off
R "whatsapp-nativefier-d40211" desktop='^3' follow=off

# Autostart Apps
nvidia-settings --assign CurrentMetaMode="nvidia-auto-select +0+0 { ForceFullCompositionPipeline = On }" &
S sxhkd
S setxkbmap -layout pt
S xsetroot -cursor_name left_ptr
S light -S 40
S setxkbmap -layout pt
S lxqt-policykit-agent
S dunst
S feh --bg-fill --randomize /mnt/Data/Wallpapers/*
#bottom left lock, top right doesnt lock
S xautolock -time 8 -locker "$HOME/.scripts/lock" -corners 0-+0  -cornerdelay 4 -cornerredelay 4
"$HOME"/.config/polybar/launch.sh &
S sct 4500
