#! /bin/sh

# killall -q picom
killall -q sxhkd
killall -q polybar

# while pfrep -u $UID -x picom >/dev/null; do sleep 1; done
# while pfrep -u $UID -x sxhkd >/dev/null; do sleep 1; done
# while pfrep -u $UID -x polybar >/dev/null; do sleep 1; done
# while pfrep -u $UID -x fehbg >/dev/null; do sleep 1; done

# Autostart Apps
# picom & 
$HOME/bin/monitor &
sxhkd &
setxkbmap -layout pt &
xsetroot -cursor_name left_ptr &
~/.config/polybar/launch
# ~/.fehbg

# Colors
AZURE="#80d9d8"
NORMAL_BORDER_COLOR="#5b5558"
ACTIVE_BORDER_COLOR="#262734"
PRESEL_FEEDBACK_COLOR="#D6A36A"

bspc monitor eDPI-1-1 -d cmd www im dev media vbox doc
bspc monitor HDMI-0 -d cmd www im dev media vbox doc

bspc config border_width          1
bspc config window_gap            18
Bspc config normal_border_color   "$NORMAL_BORDER_COLOR"
bspc config active_border_color   "$ACTIVE_BORDER_COLOR"
bspc config focused_border_color  "$AZURE"
bspc config presel_feedback_color "$PRESEL_FEEDBACK_COLOR"

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

# Application Rules
bspc rule -a st-256color      desktop='^1' follow=on
bspc rule -a firefox          desktop='^2' 
bspc rule -a Firefox-esr      desktop='^2' 
bspc rule -a TelegramDesktop  desktop='^4'
bspc rule -a Zathura          desktop='^5' state=tiled