#!/bin/bash
ibus-daemon -x -d -s &
#uppr right corner, desactivate, left, activate
xautolock -time 5 -locker 'i3lock -c 111111' -corners +-00  -cornerdelay 4 -cornerredelay 4 &
#sleep 3 && sudo $HOME/.scripts/powersaving AC &
$HOME/.scripts/touchpad_toggle &
/usr/bin/start-pulseaudio-x11 &
/usr/lib/lxpolkit/lxpolkit &
pcmanfm -d &
thunderbird &

$HOME/.scripts/drop_start
