#!/bin/bash
# Credits:
# ########
#
#
# ## Status bar options:
# http://0mark.unserver.de/projects/dwm-sprinkles/tfm
#
# ## Battery, monitor brightness cripts & lots of details:
# Jason Ryan (http://jasonwryan.com/)
#
# w0ng for providing examples that let
# resolve a few issues
#
# A few kind guys whose names I cannot recall,
# but whose work came of great help.
#
# adapted from bohoomil
#

#colors
BLUE= "#00BFFF"
WHITE="#CDCDCD"
BLACK="#000000"
ORANGE="#ff8c00"
RED="#ff0000"
GREEN="#62b786"
LIGHT_BLUE="#7DC1CF"
AZURE="#80d9d8"
LIGHT_GREEN="#76EE00"
PURPLE="#BF5FFF"
#PURPLE="#993299"
GREY="#999999"


sep1="\\$GREY\ >"

cputmp(){
    hddt="$(sensors | awk '/Physical/ {print substr($4,2,6);}')"
    echo -e "\\$ORANGE\ ${hddt}${sep1}"
}

cpu(){
  read cpu a b c previdle rest < /proc/stat
  prevtotal=$((a+b+c+previdle))
  sleep 0.5
  read cpu a b c idle rest < /proc/stat
  total=$((a+b+c+idle))
  cpu="$((100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))"
  echo -e "\\$PURPLE\ CPU $cpu%${sep1}"
}


bat(){
    batst="$($HOME/.scripts/bat.sh)"
    batt='/sys/class/power_supply/BAT1/'
    state=$(<"${batt}"/status)
    if [[ $state == 'Discharging' ]] || [[ $state == 'Charging' ]]; then
        echo -e "\\$PURPLE\ Bat ${batst}${sep1}"
    fi
}

vol(){
    level="$(awk -F"[][]" '{print $2}' <(amixer get Master) | tail -1)"
    echo -e "\\$LIGHT_BLUE\ Vol: ${level}"
}

mpd(){
  track="$(mpc current)"
  artist="${track%%- *}"
  title="${track#*- }"
  [[ -n $artist ]] && echo -e "\\$PURPLE\ $artist- $title$sep1"
}

dte(){
    dat="$(date "+%a %b %d, %R")"
    echo -e "${sep1}\\$LIGHT_GREEN\ ${dat}"
}

weather(){
    weather="$(cat /tmp/weather)"
    [[ -n $weather ]] && echo -e "\\$AZURE\ ${weather}${sep1}"
}

hddwarn(){
    warn="$(df -h | awk '/sda6/ { gsub("%","",$5) ; print $5 }')"
    [[ $warn -gt 95 ]] && echo -e "\\$RED\ BAZINGA${sep1}"
}

# pipe it
wmfs -s "$(hddwarn)$(mpd)$(weather)$(cputmp)$(cpu)$(bat)$(vol)$(dte)"


