--disable-features=BraveRewardsGemini,BraveRewardsVerboseLogging,NativeBraveWallet
#--enable-features=VaapiVideoDecoder,VaapiIgnoreDriverChecks,Vulkan,DefaultANGLEVulkan,VulkanFromANGLE,UseOzonePlatform
#--ozone-platform=wayland
--ignore-gpu-blocklist
--enable-zero-copy
--enable-gpu-rasterization