#!/bin/sh

export XDG_CONFIG_HOME="$HOME/.config"
export EDITOR=leafpad
export VDPAU_DRIVER=nvidia


if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?* ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# source Xresources
[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

# local bin
PATH=~/bin:$PATH
export PATH


WM="bspwm"

case "$WM" in
    dwm)
        "$HOME/.scripts/autostart.sh" &
        exec dwm
        ;;
    bspwm)
        exec bspwm
        ;;
esac
