#!/bin/bash

export XDG_CONFIG_HOME="$HOME/.config"
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
#export EDITOR=nano
export VDPAU_DRIVER=nvidia
export LIBVA_DRIVER_NAME=vdpau

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?* ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# source Xresources
[[ -f ~/.Xresources ]] && xrdb -merge "$HOME"/.Xresources

# local bin
PATH=~/bin:$PATH
export PATH


WM="dwm"

case "$WM" in
    dwm)
        "$HOME/Dotcats/suckless/dwm-6.2/autostart.sh" &
        exec dwm 2> /tmp/dwm.log
        ;;
    bspwm)
        exec bspwm
        ;;
esac
