#= MODULES ====================================================================
autoload -U compinit promptinit colors
compinit
promptinit
colors

zstyle ':completion:*' menu select

#---------#
# Options #
#---------#

setopt BANG_HIST                 # Treat the '!' character specially during expansion.
setopt EXTENDED_HISTORY          # Write the history file in the ":start:elapsed;command" format.
setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
setopt HIST_IGNORE_SPACE         # Don't record an entry starting with a space.
setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
setopt HIST_VERIFY               # Don't execute immediately upon history expansion.
setopt HIST_BEEP                 # Beep when accessing nonexistent history.

export TERM="xterm-256color"
export HISTFILE=~/.zsh_history
export SAVEHIST=$HISTSIZE

#export XDG_CACHE_HOME="$HOME/.cache"
#export XDG_CONFIG_HOME="$HOME/.config"
#export XDG_DATA_HOME="$HOME/.local/share"
#export XDG_STATE_HOME="$HOME/.local/state"
#export ZDOTDIR="$XDG_CONFIG_HOME"/zsh
#
#export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker
#export GNUPGHOME="$XDG_DATA_HOME"/gnupg
#export HISTFILE="$ZDOTDIR"/.zsh_history
#export KUBECONFIG="$XDG_CONFIG_HOME"/kube/config
#export KUBECACHEDIR="$XDG_CACHE_HOME"/kube
#export LESSHISTFILE="-"
#export MYSQL_HISTFILE="$XDG_CACHE_HOME"/mysql_history
#export NVM_DIR="$XDG_CONFIG_HOME"/nvm
#export PASSWORD_STORE_DIR="$XDG_DATA_HOME"/pass

## zsh-autosuggestions
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
ZSH_AUTOSUGGEST_STRATEGY=(history completion)

## oh my zsh
#ZSH=/usr/share/oh-my-zsh/
#plugins=(git history colored-man-pages)


#ZSH_CACHE_DIR=$HOME/.cache/oh-my-zsh
#if [[ ! -d $ZSH_CACHE_DIR ]]; then
#    mkdir $ZSH_CACHE_DIR
#fi

#source $ZSH/oh-my-zsh.sh

#---------#
# Aliases #
#---------#

source "$HOME/.stuff/aliases"

#-----------#
# Functions #
#-----------#

source "$HOME/.stuff/functions"
source "$HOME/.stuff/podman"
source "$HOME/.stuff/systemd"


# colors for ls
if [[ -f ~/.zsh_stuff/dir_colors ]]; then
    eval $(dircolors -b ~/.zsh_stuff/dir_colors)
fi


#---------------#
# Startup stuff #
#---------------#

#colorscript random

eval "$(starship init zsh)"

if [ "$(pgrep X)" ]
then
    #export PF_INFO="ascii title os kernel wm shell uptime pkgs memory"
    #pfetch
    nitch
fi