#!/bin/bash

# backup important things (to me). Script written in bash script
# that is executed every 1 week day (cron job)

# backup V. 0.8

#---------------------------#
#changelog

#V0.1 - first version
#V0.2 - code cleaning, add other files to backup
#V0.3 - Switch from cp to rsync (beta), a little code cleaning also
#V0.3 - Code cleaning also (using functions of bash now, still learning).
#v0.4 - Saving latex file, no alterations to code
#v0.5 - Start using kmess, so I need to backup the logs as well
#v0.6 - change the local of conky files
#v0.7 - Completely rebuild of the script (change to systemd, using tmp instead of disk to copy the files, etc)
#v0.8 - Some things I don't need -> change to github

#Variables

MAIN_FOLDER="/mnt/Data/My Files/Linux/Backup files"
USER_FOLDER=/home/ilusi0n
TEMP_FOLDER=/tmp/backup

function main() {

# copy the folder and compact to the dropbox folder and delete recrusively the folder
cd /tmp
tar -cf backup.tar backup
rsync -a /tmp/backup.tar $USER_FOLDER/Dropbox/Linux/
rsync -a --delete /tmp/backup.tar "$MAIN_FOLDER"
rm -r $TEMP_FOLDER
rm -r backup.tar
}

#create temporary folders

function createFiles() {

mkdir -p /tmp/backup
cd $TEMP_FOLDER
mkdir Pidgin
mkdir ArchFiles
mkdir systemdFiles
}

#backup pidgin logs & contacts
#other files related to personalization

function otherThings() {

PIDGIN_FOLDER=/home/ilusi0n/.purple
#pidgin
cp -r $PIDGIN_FOLDER/logs $TEMP_FOLDER/Pidgin/
cp $PIDGIN_FOLDER/blist.xml $TEMP_FOLDER/Pidgin/
#latex
cp -r $USER_FOLDER/Documentos/LaTeX/ $TEMP_FOLDER/

}

#important files

function importantFiles() {

cp /etc/{mpd.conf,vconsole.conf,hostname,sudoers,fstab,locale.conf,asound.conf} $TEMP_FOLDER/ArchFiles
cp /etc/systemd/system/{dropboxd.service,phc-intel.service} $TEMP_FOLDER/systemdFiles

}

# Program, main. Functions called

createFiles
otherThings
importantFiles
main

exit 0
