#!/bin/bash

case "$1" in
	up)
		pamixer -u > /dev/null 2>&1
		pamixer -i 5  > /dev/null 2>&1
		;;
	down)
		pamixer -u > /dev/null 2>&1
		pamixer -d 5  > /dev/null 2>&1
		;;
	toggle)
		pamixer -t  > /dev/null 2>&1
		;;
	*)
		echo $"Usage: $0 {up|down|toggle}"
            exit 1
esac