#!/bin/bash
OMG="EUR|pt|11|Lisbon"
METRIC=1 #Should be 0 or 1; 0 for F, 1 for C

weather="$(curl -s http://rss.accuweather.com/rss/liveweather_rss.asp\?metric\=${METRIC}\&locCode\=${OMG} | perl -ne 'if (/Currently/) {chomp;/\<title\>Currently: (.*)?\<\/title\>/; print "$1"; }')"

case "$weather" in
    *"Sunny"*) echo  "$weather" ;;
    *"Mostly Clear"*) echo  "$weather" ;;
    *"Mostly Cloudy"*) echo  "$weather" ;;
    *) echo "$weather" ;;
esac
