#!/bin/sh
#AccuWeather (r) RSS weather tool for conky
#
#USAGE: weather.sh <locationcode>
#
#(c) Michael Seiler 2007
# Lisbon EUR|pt|11|Lisbon

METRIC=1 #Should be 0 or 1; 0 for F, 1 for C
OMG="EUR|pt|11|Lisbon"

#if [ -z $1 ]; then
#    echo
#    echo "USAGE: weather.sh <locationcode>"
#    echo
#    exit 0;
#fi
     
#curl -s http://rss.accuweather.com/rss/liveweather_rss.asp\?metric\=${METRIC}\&locCode\=$1 | perl -ne 'if (/Currently/) {chomp;/\<title\>Currently: (.*)?\<\/title\>/; print "$1"; }'

curl -s http://rss.accuweather.com/rss/liveweather_rss.asp\?metric\=${METRIC}\&locCode\=${OMG} | perl -ne 'if (/Currently/) {chomp;/\<title\>Currently: (.*)?\<\/title\>/; print "$1"; }'




